### ISSUE TITLE
Webpack server is not starting.. 

### ISSUE THREAD

**Issue by chandravyas** [shardis/spring-angular2-starter#10]
I am getting below error when trying to run "npm run start" command on 'shardis-ui' package.

const {ENV, validateConfig, baseWebpackConfig, absolutePath} = require('./webpack.commons.js');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/<User>/Desktop/spring-angular2-starter-master/shardis-ui/node_modules/webpack/bin/convert-argv.js:93:13)
    at Object.<anonymous> (/Users/<User>Desktop/spring-angular2-starter-master/shardis-ui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:121:48)
    at Module._compile (module.js:409:26)

**Comment by kucharzyk** [comment]
This error is caused by too old node version.
This project installs v6.2.0 via maven frontend plugin.

You can upgrade your local node to v6.2.0 but better way is to use node installed by maven.
In shardis-ui directory there are shortcuts npm and npm.cmd for using this node version

Try using ```./npm run start``` instead of ```npm run start``` 

If you updated repo from some older version you should also remove ./shardis-ui/node and ./shardis-ui/node_modules directories and rebuild the project

**Comment by chandravyas** [comment]
Thank you.. "./npm run start" worked :)
